# Post :: Create
POST {{baseUrl}}/posts HTTP/1.1
content-type: application/json
 
{
  "title": "new post",
  "body": "new post body",
  "tags": ["tag1", "tag2"]
}

###

# Post :: Read All
GET {{baseUrl}}/posts HTTP/1.1
content-type: application/json
 
###

# Post :: Read All with query (check mongoose-query-parser library)
GET {{baseUrl}}/posts?tags=hot HTTP/1.1
content-type: application/json
 
###

# Post :: Read One
GET {{baseUrl}}/posts/1ab97c9f-9e4e-473b-923d-9b08051255ec HTTP/1.1
content-type: application/json

###

# Post :: Update One
PATCH {{baseUrl}}/posts/7086e67fss-791f-48ee-ae7f-61cf1cd1aa93 HTTP/1.1
content-type: application/json

{
  "title": "Updated title 2"
}

###

# Post :: Delete one 
DELETE {{baseUrl}}/posts/7086e67f-791f-48ee-ae7f-61cf1cd1aa93 HTTP/1.1
content-type: application/json
